### ISSUE TITLE
Plugin not added to page in Django CMS 3.4.1

### ISSUE THREAD

**Issue by iainhouston** [bitmazk/cmsplugin-markdown#11]
-  I installed the packages; 
-  I edited`settings.py`; 
-  I ran a migration; 
    -  I didn't see any markdown plugin to add to a placeholder; 
-  ran a migration again. 
   -  still don't see the markdown plugin; 

**Q:** How can I tell what I'm doing wrong?  

    # ./manage.py migrate                   
    Operations to perform:
      Synchronize unmigrated apps: djangocms_admin_style, cmsplugin_markdown, sitemaps, treebeard, staticfiles, cmsplugin_filer_utils, messages, sekizai, django_markwhat, mycms
      Apply all migrations: djangocms_snippet, filer, admin, sessions, easy_thumbnails, cmsplugin_filer_image, cmsplugin_filer_folder, djangocms_text_ckeditor, djangocms_video, sites, cmsplugin_filer_file, contenttypes, djangocms_column, djangocms_link, menus, auth, djangocms_googlemap, cms, djangocms_style
    Synchronizing apps without migrations:
      Creating tables...
        Creating table cmsplugin_markdown_markdownplugin
        Running deferred SQL...
      Installing custom SQL...
    Running migrations:
      No migrations to apply.

    # ./manage.py migrate cmsplugin_markdown                                                                                       
    Operations to perform:
      Apply all migrations: (none)
    Running migrations:
      No migrations to apply.

**Comment by Tyrdall** [comment]
@iainhouston Just updated the app with new migrations. Can you please update and try again?

**Comment by iainhouston** [comment]
@Tyrdall Now Markdown plugin appears in list but subsequent window is empty and *Save* has no effect.

This is what I did:

    $ pip install -e git://github.com/bitmazk/cmsplugin-markdown.git#egg=cmsplugin_markdown
    Obtaining cmsplugin_markdown from git+git://github.com/bitmazk/cmsplugin-markdown.git#egg=cmsplugin_markdown
      Cloning git://github.com/bitmazk/cmsplugin-markdown.git to /Users/iainhouston/.virtualenvs/django-cms-docker/src/cmsplugin-markdown
    Requirement already satisfied (use --upgrade to upgrade): Django in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-cms in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): Markdown in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-markwhat in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-sekizai>=0.7 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-cms->cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-formtools>=1.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-cms->cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-classy-tags>=0.7.2 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-cms->cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): django-treebeard>=4.0.1 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-cms->cmsplugin_markdown)
    Requirement already satisfied (use --upgrade to upgrade): djangocms-admin-style>=1.0 in /Users/iainhouston/.virtualenvs/django-cms-docker/lib/python3.5/site-packages (from django-cms->cmsplugin_markdown)
    Installing collected packages: cmsplugin-markdown
      Running setup.py develop for cmsplugin-markdown
    Successfully installed cmsplugin-markdown-0.1.4

    $ grep -n mark  mycms/settings.py 
    151:    'django_markwhat',
    152:    'cmsplugin_markdown',

    $ ./manage.py migrate cmsplugin_markdown
    Operations to perform:
      Apply all migrations: cmsplugin_markdown
    Running migrations:
      Rendering model states... DONE
      Applying cmsplugin_markdown.0001_initial... OK

This is what I saw:  

<img width="1017" alt="screen shot 2016-10-28 at 10 43 34" src="https://cloud.githubusercontent.com/assets/537596/19802582/53a0105c-9cfc-11e6-885b-d664a74fc09b.png">
<img width="1017" alt="screen shot 2016-10-28 at 10 43 34" src="https://cloud.githubusercontent.com/assets/537596/19802588/573e6998-9cfc-11e6-852e-8b69e030b83e.png">

**Comment by Tyrdall** [comment]
@iainhouston EpicEditor is not working. I'm on it.

**Comment by Tyrdall** [comment]
@iainhouston Should be fixed in v0.1.5
