### ISSUE TITLE
Table name problem

### ISSUE THREAD

**Issue by darbula** [bitmazk/cmsplugin-markdown#7]
After installation in project wth django cms 3.1.3 following error occurs:

```
no such table: cmsplugin_markdown_markdownplugin
```

Renaming table fixes this problem. probably [this change](http://django-cms.readthedocs.org/en/latest/upgrade/3.0.html#no-more-db-tablename-magic-for-plugins) is responsible.

**Comment by Tyrdall** [comment]
The migrations create a table called ``cmsplugin_markdownplugin``: https://github.com/bitmazk/cmsplugin-markdown/blob/master/cmsplugin_markdown/migrations/0001_initial.py#L13

Since South migrations are already deprecated it wouldn't make sense to adjust the old migrations now.
Do you want to create a pull request, which adds support for Django>1.7?

**Comment by darbula** [comment]
In filer cmsplugins they renamed tables in South migrations here  https://github.com/stefanfoulis/cmsplugin-filer/commit/799ba2f5fe972496e994459551f065a18188f3f4 using this module https://github.com/stefanfoulis/cmsplugin-filer/blob/develop/cmsplugin_filer_utils/migration.py

**Comment by Tyrdall** [comment]
Which Django version are you using?

**Comment by darbula** [comment]
Django 1.6.10

**Comment by darbula** [comment]
Ofcourse, but I stumbled on two new issues: (1) jQuery/$ is undefined in script in change_form.html, I have solved this, but then (2) <div id="epiceditor"> placed in {% block top %} does not appear since in parent templates there is no block named top.

**Comment by Tyrdall** [comment]
Alright, this block has been removed a long time ago: https://github.com/divio/django-cms/commit/e61f9f05fa35dce912381f2cebb9422caedab1ec#diff-467b8fc096d19b08b848554c37c11ffaL39

Changing it to the following might work:

    {% block object-tools %}
        <div id="epiceditor"></div>
        {{ block.super }}
    {% endblock %}

I'm sorry, this app hasn't been used very often :(

**Comment by darbula** [comment]
I see, no problem. The thing is that I stumbled on further issues with epiceditor and have moved to other editor. I plan to continue work in my considerably different fork and send you a pull request just for this issue.

**Comment by Tyrdall** [comment]
Awesome! Looking forward to it!

**Comment by Tyrdall** [comment]
Thanks @darbula!
