### ISSUE TITLE
EpicEditor not working

### ISSUE THREAD

**Issue by zanderle** [bitmazk/cmsplugin-markdown#9]
EpicEditor isn't working for me.

I also tried changing the `change_form.html` template to:

```
{% extends "admin/cms/page/plugin/change_form.html" %}

{% block after_field_sets %}<div id="epiceditor"></div>{% endblock %}


{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}cmsplugin_markdown/themes/base/epiceditor.css" />
{% endblock %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script src="{{ STATIC_URL }}cmsplugin_markdown/js/epiceditor.min.js"></script>
<script>
(function($) {
    $('#markdownplugin_form>div').hide();
    var opts = {
        basePath: '{{ STATIC_URL }}cmsplugin_markdown'
        ,clientSideStorage: false
    };
    var editor = new EpicEditor(opts).load();
    var text = $(editor.getElement('editor').body);
    text.html($('#id_markdown_text').html().replace(/\n/g, '<br />'));
    text.keyup(function () {
        $('#id_markdown_text').val(editor.exportFile(null, 'text'));
    });
})(django.jQuery);

</script>
{% endblock %}
```

which at least made the EpicEditor load, but it doesn't show up. Any ideas?

I am using Django 1.8 and DjangoCMS 3.2.

**Comment by Tyrdall** [comment]
Unfortunately we're not using this app at the moment and I don't have the time to create an update. We need to debug the JS code and actually I don't know, if this epic editor version is working at all.

**Comment by zanderle** [comment]
I see. I might be able to contribute when I have more time. Or I can fork this, if you won’t have time to maintain it anymore?

**Comment by Tyrdall** [comment]
Sure!

**Comment by mbrochh** [comment]
@zanderle if you send a pull request, we will test it quickly and merge it, usually within a few days. If we don't know how to test it, we will ask you ;)

**Comment by JurajKavka** [comment]
i google chrome 

`(index):33 Uncaught TypeError: $ is not a function`

i'm looking forward to fix. :) thank you!!

**Comment by Flimm** [comment]
This fork fixes this issue: https://github.com/niconoe/djangocms-markdown

**Comment by Tyrdall** [comment]
@Flimm this is not a fork of this app.

**Comment by Flimm** [comment]
@Tyrdall Actually it is. https://github.com/niconoe/djangocms-markdown is a fork of https://github.com/ovidner/djangocms-markdown , which is a fork of https://github.com/ovidner/djangocms-markdown , which is a fork of https://github.com/USGM/cmsplugin-markdown , which is a fork of https://github.com/bitmazk/cmsplugin-markdown .

**Comment by Tyrdall** [comment]
@Flimm Hahaha, alright. Never seen something like that before :)

**Comment by Tyrdall** [comment]
Should be fixed now.
